name: Scheduled Python Script Execution

on:
  schedule:
    # UTC 12:00
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Removing previous chrome instances on runner 
      run: |
          sudo apt purge google-chrome-stable  
        
       # Need to fetch reqs if needed
    - name: Installing all necessary packages
      run: |
          pip install -r requirements.txt

    - name: Run script
      run: python scripts/gpts.py

    - name: Commit files
      run: |
        git config --local user.email "gpts.open@gmail.com"
        git config --local user.name "opengpts"
        git add -A
        DATE=$(date -u +"%Y-%m-%d")
        git commit -m "Add Today's ($DATE) ranking" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
